version: "3"

services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    links:
      - server
    ports:
      - "80:8080"

    